include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Every public symbol of the package is documented.
    - public_member_api_docs
    - always_declare_return_types
    - prefer_final_locals
    - prefer_single_quotes
    - sort_constructors_first
    - unawaited_futures
